{  
   "swagger":"2.0",
   "info":{  
      "description":"Home Monitor Arduino",
      "title":"Home Monitor Arduino",
      "version":"1.0.0"
   },
   "host":"home-monitor-arduino.appspot.com",
   "basePath":"/",
   "consumes":[  
      "application/json"
   ],
   "produces":[  
      "application/json"
   ],
   "schemes":[  
      "https"
   ],
   "paths":{  
      "/device":{  
         "get":{  
            "description":"Get Device",
            "operationId":"getDevice",
            "produces":[  
               "application/json"
            ],
            "responses":{  
               "200":{  
                  "description":"Created or Updated Device"
               }
            }
         },
         "post":{  
            "description":"Create or Update a Device",
            "operationId":"postDevice",
            "produces":[  
               "application/json"
            ],
            "responses":{  
               "200":{  
                  "description":"Created or Updated Device"
               }
            },
            "security":[  
               {  
                  "api_key":[  

                  ]
               }
            ]
         },
         "put":{  
            "description":"Create or Update a Device",
            "operationId":"putDevice",
            "produces":[  
               "application/json"
            ],
            "responses":{  
               "200":{  
                  "description":"Created or Updated Device"
               }
            },
            "security":[  
               {  
                  "api_key":[  

                  ]
               }
            ]
         }
      },
      "/device/{id}":{  
         "delete":{  
            "description":"Delete one Device",
            "operationId":"deleteDevice",
            "produces":[  
               "application/json"
            ],
            "parameters":[  
               {  
                  "name":"id",
                  "in":"path",
                  "type":"string"
               }
            ],
            "responses":{  
               "200":{  
                  "description":"One Device"
               }
            },
            "security":[  
               {  
                  "api_key":[  

                  ]
               }
            ]
         }
      },
      "/devicereport":{  
         "post":{  
            "description":"Create or Update a DeviceReport",
            "operationId":"postDeviceReport",
            "produces":[  
               "application/json"
            ],
            "responses":{  
               "200":{  
                  "description":"Created or Updated DeviceReport"
               }
            },
            "security":[  
               {  
                  "api_key":[  

                  ]
               }
            ]
         },
         "put":{  
            "description":"Create or Update a DeviceReport",
            "operationId":"putDeviceReport",
            "produces":[  
               "application/json"
            ],
            "responses":{  
               "200":{  
                  "description":"Created or Updated DeviceReport"
               }
            },
            "security":[  
               {  
                  "api_key":[  

                  ]
               }
            ]
         }
      }
   },
   "securityDefinitions":{  
      "api_key":{  
         "type":"apiKey",
         "name":"key",
         "in":"query"
      }
   }
}
